name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: git config user.email "harrysolovay@gmail.com"
      - run: git config user.name "Harry Solovay"
      - run: yarn beachball publish -m 'chore{{:}} release new version' release -n $NPM_TOKEN -y
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
